version: '3'
services:
  hyperf-skeleton:
    container_name: meuatelie
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: ana
      MYSQL_PASSWORD: novasenha
      MYSQL_DATABASE: meuAtelie
      MYSQL_ROOT_PASSWORD: qualquer
    ports:
      - "3307:3306"

networks:
  default:
    name: hyperf-skeleton
